language: rust
rust:
- nightly
sudo: false
notifications:
  email:
    on_success: never
    on_failure: change
addons:
  apt:
    packages:
    - nasm
script:
- make
after_success: curl https://raw.githubusercontent.com/kmcallister/travis-doc-upload/master/travis-doc-upload.sh | sh

