language: rust
rust:
- nightly
sudo: false
notifications:
  email:
    on_success: never
    on_failure: change
addons:
  apt:
    packages:
    - nasm
script:
- make
after_success: scripts/travis-doc-upload.sh
